### ISSUE TITLE
Dropdowns in tree should align properly when aligned right

### ISSUE THREAD

**Issue by taemon1337** [blackat/ui-navbar#1]
If you add the class 'pull-right' to a bootstrap navbar link with a dropdown, then each subtree/submenu should also have the 'pull-right' class which bootstrap uses to align the dropdown menu to the left so that it does not show offscreen.

I am able to add the 'pull-right' class at the top level, but any subtree defined by JSON does not add this class.  Should be an easy fix.

I'd suggest doing something like this (not tested) in the link function

``` javascript
            link: function (scope, element, attrs) {
                if (angular.isArray(scope.leaf.subtree)) {
                    element.append('<tree tree=\"leaf.subtree\"></tree>');
                    element.addClass('dropdown-submenu');
                    // THE FOLLOWING LINE IS THE CHANGE
                    if(element.parents('ul.nav').hasClass('pull-right')) { element.addClass('pull-right'); }
                    $compile(element.contents())(scope);
                }
            }
```

**Comment by blackat** [comment]
Hi,
you are right there is an issue, thanks a lot for your fix, I will try to report it by a couple of days and I will release a new version. 

I keep you posted.

Have a nice day ;-)

**Comment by blackat** [comment]
**update:** I have dived into the issue and it is not so simple:
- according to twitter bootstrap add the tag `navbar-right` when you want to push to the right a dropdown link;
- I have changed a bit the css in order to get the submenu open on the left otherwise the submenu will be not totally visible or not visible at all;

I need to find a way to correctly and easily add the new css class where required in the directive.

Thanks for the patience ;-)

**Comment by blackat** [comment]
Hi,
I have fixed the issue, check please on [Plunkr](http://plnkr.co/edit/V7tecYv4wNPP198HRQlJ?p=preview) if it works as you were expecting, and update to version 0.2.4.

Thanks ;-)
