### ISSUE TITLE
Top level menu generation dynamically

### ISSUE THREAD

**Issue by asfiqbal** [blackat/ui-navbar#18]
It seems that dynamic menu generation always require at least one top level menu hard coded! For example.

```
<li uib-dropdown="">
     <a href="#" uib-dropdown-toggle="">
           Report
            <span class="caret"></span>
      </a>
      <tree tree="tree"></tree>
</li>
```

Provided demo also have top level hard coded menus. It seems am missing something as dynamic top level menu requirement is very basic. I like to use in following way.

```
<ul class="nav navbar-nav">
        <tree tree="tree"></tree>
</ul>
```

Please let me know how i could use the module in above stated way.

**Comment by blackat** [comment]
@asfiqbal thanks a lot for the interest in the module, unfortunately it is not possible to do that, I need an anchor or a button to activate the dropdown.
If I have well understood what you mean, you should have the name of the item menu directly inside of the tree array but it must be the root and component is not implemented in this way yet.

Another option is to use it for a drop down button or drop down icon, [here](http://plnkr.co/edit/CTizS3eJaApAKcYPnVR5?p=preview) you can find an example.

Hepe it helps

**Comment by blackat** [comment]
@asfiqbal I have added a directive to manage all the tree so it is enough to pass an array of well formatted states that you can dynamically manage and the directive should do the job:

``` html
<ul class="nav navbar-nav">
    <trees trees="trees"></trees>
</ul>
```

I have not released it yet because I would like to improve the documentation a bit more, but if you want you can take the `release` folder, the `.js` or `.min.js`, templates are inside them. The demo has been updated to show how to use it, it should be more straight forward.

Please, let me know if it satisfies your requirements.

Regards 😉

**Comment by blackat** [comment]
@asfiqbal published version 0.5.2 with updated documentation, please have a look at it.

**Comment by asfiqbal** [comment]
This is great and exactly what i wanted, thanks a lot :)

**Comment by blackat** [comment]
you're welcome :wine_glass:
