### ISSUE TITLE
show loading icon by creating directive

### ISSUE THREAD

**Issue by ghost** [blackat/ui-navbar#7]
Hello,

I found a directive to add loading icon by creating directive:

(function(app) {
 var routeLoadingIndicator = function($rootScope) {
    return {
      restrict: 'E',
      template: "<div class='col-lg-12' ng-if='isRouteLoading'><h1>Loading <i class='fa fa-cog fa-spin'></i></h1></div>",
      link: function(scope, elem, attrs) {
        scope.isRouteLoading = false;
        $rootScope.$on('$routeChangeStart', function() {
          scope.isRouteLoading = true;
        });
        $rootScope.$on('$routeChangeSuccess', function() {
          scope.isRouteLoading = false;
        });
      }
    };
  };
  routeLoadingIndicator.$inject = ['$rootScope'];
  app.directive('routeLoadingIndicator', routeLoadingIndicator);
}(angular.module('route-change-loader')));

By it does not work!!!

here is the link:

http://www.technofattie.com/2014/07/27/easy-loading-indicator-when-switching-views-in-angular.html

**Comment by blackat** [comment]
Hi,
as far as I see from the link you have posted, the example makes use of angular router (`$routeChangeStart`, `$routeChangeSuccess` etc) while the component ui-navbar makes use of ui.router as you can notice from the documentation so, I guess, because of this it does not work.

Then, just an advice, next time you post here or somewhere else you should create a plunkr or jsfiddle or whatever web app to share the code.

I have already suggested you how to do it. If you plan to use [spin.js](http://fgnass.github.io/spin.js/) as in the example, the best is to create a directive, watch the model that should be true by default when you open the page and then set to false when data have been loaded, just an idea.

Sorry but for the time being I am not planning to make an improvement such this one, Angular2 is already taking a lot of my free time :wink:
